 # -*- coding: utf-8 -*-
{'name': 'Property Management',
  'version': '13.0',
  'category': 'Property',
  'summary': 'Property Managment for Real Estate Business',
  'depends': ['base',
  			  'account',
              'product',
              'crm','report_xlsx',
              'project',
              'analytic',
              'mail',
              'resource',


              ],
  'description': '''Contract, Property, Unit, Tenant, Renewal''',
  'website': 'http://www.apps-gate.net',
  'author': 'APPSGATE FZC LLC',
  'data': [
            'views/base.xml',
            'security/ir.model.access.csv',
            'views/property_type.xml',
            'views/property_view.xml',
            'views/main_property_view.xml',
            'views/property_booking.xml',
            'views/property_booking_sales.xml',
            'views/property_contract.xml',
            'views/property_contract_sales.xml',
            'wizard/property_cheque_view.xml',
            'views/property_cheque.xml',
            'views/unit_sub_type_view.xml',
            'views/unit_type_view.xml',
            'views/unit_usage_view.xml',
            'views/unit_view_view.xml',
            'views/floor_view.xml',
            'views/unit_view.xml',
            'views/document_type.xml',
            'views/property_agreement_new.xml',
            'views/account_cost_center.xml',
            'views/property_template.xml',
            'views/res_config.xml',
            'views/warning_wiz_view.xml',
            'views/property_contract_closure.xml',
            'views/property_vat_payment_line.xml',
            'views/property_agreement_closure.xml',
            'views/cashflow_report_view.xml',
            'views/od_unit_occupied_report_view.xml',
            # 'views/templates.xml',
            'views/contract_portal_templates.xml',
            'views/booking_portal_templates.xml',
            'views/salesbooking_portal_templates.xml',
            'views/sales_contract_portal_templates.xml',


            'wizard/property_floor_view.xml',
            'wizard/contract_revenue_calculation_wizard_view.xml',
            'wizard/property_unit_view.xml',
            'wizard/contract_rent_generation_wizard_view.xml',
            'wizard/agreement_rent_generation_wizard_view.xml',
            'wizard/agreement_revenue_calculation_wizard_view.xml',
            'wizard/unit_availability_checking_report_view.xml',
            'wizard/cash_flow_report_wizard_view.xml',
            'wizard/cash_flow_new_view.xml',
            'wizard/od_unit_occupied_wizard_view.xml',

            'report/report_unit_report.xml',
            'report/od_revenue_sheet_view.xml',
            'report/expiry_analysis.xml',
            'report/report_property_contract.xml',
            'report/report_property_contract_sales.xml',
            'report/report_property_booking.xml',
            'report/report_property_booking_sales.xml',
            'report/report.xml',

      # 'reports/property_payment_vat_print.xml',
           ],
  'assets': {
        'web._assets_primary_variables': [
            # 'account/static/src/scss/variables.scss',
        ],
        'web.assets_backend': [
            'ag_property_maintainence/static/library/lightbox/css/lightbox.css',
            'ag_property_maintainence/static/src/css/hoverbox.css',
            
            'ag_property_maintainence/static/library/lightbox/js/jquery.lightbox.js',
            'ag_property_maintainence/static/src/js/multi_image.js',
            'https://maps.googleapis.com/maps/api/js?key=AIzaSyBbiUIwapXRbAfwXgzbSyLI1J-29-OsY3k',
            'ag_property_maintainence/static/src/js/location-picker.min.js',
            'ag_property_maintainence/static/src/js/angular.min.js',
            'ag_property_maintainence/static/src/js/google-map.js',
            # 'https://unpkg.com/location-picker/dist/location-picker.min.js',
            # 'ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js',
            # 'ag_property_maintainence/static/src/js/map.js',
            # 'https://unpkg.com/location-picker/dist/location-picker.min.js',
        ],
        'web.assets_frontend': [
            'account/static/src/js/contract_portal_sidebar.js',
            'account/static/src/js/booking_portal_sidebar.js',
            'account/static/src/js/salesbooking_portal_sidebar.js',
            'account/static/src/js/sales_contract_portal_sidebar.js',
        ],
        'web.assets_tests': [
            # 'account/static/tests/tours/**/*',
        ],
        'web.qunit_suite_tests': [
            # ('after', 'web/static/tests/legacy/views/kanban_tests.js', 'account/static/tests/account_payment_field_tests.js'),
            # ('after', 'web/static/tests/legacy/views/kanban_tests.js', 'account/static/tests/section_and_note_tests.js'),
        ],
        'web.assets_qweb': [
            # 'account/static/src/xml/**/*',
        ],
    },
  'qweb': ["static/src/xml/image_multi.xml"],
  'installable': True,
  'application': True,
 }